image: "rust:latest"

<<<<<<< HEAD
check:cargo:
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo check --verbose --package base_engine_library

build:cargo:
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo build --verbose --package base_engine_library

test:cargo:
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --verbose --no-default-features --no-fail-fast --package base_engine_library
=======
build:cargo:
  script:
    - rustc --version && cargo --version  # Print version info
    - cargo build --verbose --release --package platform_linux

test:cargo:
  script:
    - rustc --version && cargo --version  # Print version info
    - cargo test --verbose --release --no-default-features --no-fail-fast --package platform_linux
>>>>>>> upstream/main
